### ISSUE TITLE
Barebones Commander

### ISSUE THREAD

**Issue by Jaeyoung-Lim** [DISCOWER/PX4-Space-Systems#6]

**Comment by Pedro-Roque** [comment]
Any chance of avoiding re-designing or making a barebones commander, so that we can keep in-sync with PX4 main? Or too much work for that?

**Comment by Jaeyoung-Lim** [comment]
@Pedro-Roque One way is to get rid of commander as a whole, and then try to use the output module directly

**Comment by Pedro-Roque** [comment]
Maybe we don't need this anymore? We just need to test it to ensure we don't get into weird modes that we shouldn't be in (like "Landing")
